standort:
  name: Udo
  domain: udo.myhems.org

geraete:
  shelly_pv:       "192.168.188.24"
  shelly_netz:     "192.168.188.70"
  shelly_marstek:  "192.168.188.35"
  shelly_heizstab: "192.168.188.76"
  marstek_ip:      "192.168.188.46"
  marstek_port:    30000

heizstab:
  relais: [2000, 2000, 2000]   # 3x2kW → 3 Stufen: 2/4/6kW

regelparameter:
  min_pv:            500
  min_soc:           30
  lade_schwelle:     1000
  entlade_schwelle:  1000
  hysterese:         200
  delay:             60
  poll_intervall:    5
  soc_cache_max:     60
